### ISSUE TITLE
[Question] How to run the background job?

### ISSUE THREAD

**Issue by longnd** [foreverLoveWisdom/google_search_extractor#16]
Issue
---
The application uses a [background job](https://github.com/foreverLoveWisdom/google_search_extractor/blob/develop/app/jobs/keyword_scraping_job.rb) to process the CSV file parsing and keyword crawling, but there is no queuing backend (e.g. [Sidekiq](https://github.com/mperham/sidekiq/wiki/Active-Job)) specified.
How can the feature can be tested on local?

**Comment by foreverLoveWisdom** [comment]
* For the development/test process, I use the default Active Job Async in Rails, so it is processed automatically without setting up a separate infrastructure such as Redis... 
* However, for production, I will use Sidekiq since Active Job Async is only suitable for test/dev, and small jobs, like sending emails, will be lost after restarting.
* Currently, the way I test it locally is validating if a job is enqueued after the user uploads the CSV file successfully(there is a case for if the file fails to upload as well):
```
it 'enqueue scraping job' do
  expect do
    upload_csv
  end.to change(ActiveJob::Base.queue_adapter.enqueued_jobs, :size).by(1)
end
```
* And it is tested in the [request test for](https://github.com/foreverLoveWisdom/google_search_extractor/blob/develop/spec/requests/api/v1/keywords_api_spec.rb) in the keyword API spec file.

**Comment by longnd** [comment]
> I use the default Active Job Async in Rails

but that queue adapter is not defined anywhere. At least, it should be defined in https://github.com/foreverLoveWisdom/google_search_extractor/blob/main/config/application.rb, e.g.
```
config.active_job.queue_adapter = :async
```

I'm curious without a queue backend specified like that, how did you manage to run the background jobs on your local?

**Comment by foreverLoveWisdom** [comment]
> > I use the default Active Job Async in Rails
> 
> but that queue adapter is not defined anywhere. At least, it should be defined in https://github.com/foreverLoveWisdom/google_search_extractor/blob/main/config/application.rb, e.g.
> 
> ```
> config.active_job.queue_adapter = :async
> ```
> 
> I'm curious without a queue backend specified like that, how did you manage to run the background jobs on your local?

- 👋 Hi @longnd, thanks for the follow-up questions.
- I had the same question as you when you asked me the first time. :grinning: 
- I looked at the configuration file and saw no configuration for `async`. So, I thought they probably set a default option inside the active_job lib. However, I did not spend time to validate that assumption since I wanted to focus on improving the feature, which is a higher priority. :smile: 
- Now that you have asked, I spent more time digging into the source code, and I found this configuration in Rails that proves my validation is correct:
```ruby
# frozen_string_literal: true

require "active_support/core_ext/string/inflections"

module ActiveJob
  # The <tt>ActiveJob::QueueAdapter</tt> module is used to load the
  # correct adapter. The default queue adapter is the +:async+ queue.
  module QueueAdapter # :nodoc:
    extend ActiveSupport::Concern

    included do
      class_attribute :_queue_adapter_name, instance_accessor: false, instance_predicate: false
      class_attribute :_queue_adapter, instance_accessor: false, instance_predicate: false

      delegate :queue_adapter, to: :class

      self.queue_adapter = :async
    end
.........
```
- The source code can be found [here](https://github.com/rails/rails/blob/main/activejob/lib/active_job/queue_adapter.rb)
- Another way we can test this assumption is in `rails console`:
```ruby
ActiveJob::Base.queue_adapter_name
=> "async"
```
- This adapter runs background jobs in the same process as the Rails server, so as long as the local Rails server is running, the jobs will be processed automatically without any further setup on the local development. 

- However, as I have mentioned before, I would use `Sidekiq` on production instead because `async` may not be suitable for production environments or large-scale applications that require more robust job processing. In those cases, it's often better to use a separate queue backend, such as Sidekiq or Resque.

- I hope this clears things up for you! Let me know if you have any follow-up questions or if there's anything else I can help you with. 😊

**Comment by longnd** [comment]
good finding. Thank you for the effort and sharing.
