### ISSUE TITLE
[Question] Why does the app need jQuery

### ISSUE THREAD

**Issue by longnd** [foreverLoveWisdom/google_search_extractor#20]
Issue
---
As part of the commit 13930f9, jQuery is added to the app. Is it used anywhere? If it hasn't been used yet, I'm curious why you decided to pick jQuery instead of Vanilla JS or Stimulus.

**Comment by foreverLoveWisdom** [comment]
> Is it used anywhere? 
>
* I added jQuery because I wanted to use it to manipulate any HTML/CSS later. Plus, I remember Bootstrap depends on jQuery to work correctly, but I just did a quick search, and it turns out the latest version(5) doesn't depend on jQuery. Finally, the reason you don't see it used elsewhere because I didn't have time to work on it, and I want to focus on the backend and tests(unit tests and feature tests) instead 😊

>  If it hasn't been used yet, I'm curious why you decided to pick jQuery instead of Vanilla JS or Stimulus.
>
* Since the frontend is not my strength, I should choose the tool that allows me to work the fastest, especially for the code challenge; I want to play it safe here. 😂 
* But if the project requires me to learn Vanilla JavaScript or Stimulus, I am willing to learn it. I have spent time playing with functional programming in JS, so I am curious about how to apply it on the frontend side. ❤️ 

* So, would you like me to remove the jQuery code from the project?

**Comment by longnd** [comment]
it is not needed. I know the reason now. Thank you for the clarification.
